[book]
authors = ["IFcoltransG"]
language = "en"
multilingual = false
src = "src"
title = "Esoteric Python Guide"

[output.html]
git-repository-url = "https://github.com/IFcoltransG/esoteric-python-guide/"
edit-url-template = "https://github.com/IFcoltransG/esoteric-python-guide/edit/master/{path}"
